(function(g){var window=this;'use strict';var $3=function(a){a.ma("cardstatechange",a.uj()&&a.Zn()?1:0)},a4=function(a,b){var c=g.Ha(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},Bbb=function(a){var b=g.Ol(a);
a=g.Xl(a);return new g.Dl(b.x,b.y,a.width,a.height)},Cbb=function(a){return Math.pow(a,3)},Dbb=function(a){return 3*a*a-2*a*a*a},d4=function(a){a=g.Oa(a);
delete b4[a];g.Rc(b4)&&c4&&c4.stop()},Fbb=function(){c4||(c4=new g.no(function(){Ebb()},20));
var a=c4;a.isActive()||a.start()},Ebb=function(){var a=g.Ra();
g.Gc(b4,function(b){Gbb(b,a)});
g.Rc(b4)||Fbb()},e4=function(a,b,c,d){g.Ho.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.V=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.J=0;this.D=null},Gbb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.D);a.D=b;Hbb(a,a.progress);1==a.progress?(a.j=0,d4(a),a.onFinish(),a.xq()):a.bd()&&a.vI()},Hbb=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.V[c]-a.u[c])*b+a.u[c]},Ibb=function(a,b){g.eb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},f4=function(a,b,c,d,e){e4.call(this,b,c,d,e);
this.element=a},Jbb=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
f4.call(this,a,b,c,d,e)},Kbb=function(a){g.C.call(this);
this.u=a||window;this.j=[]},g4=function(a){return a.baseUrl||null},h4=function(a,b){return g.Hm(g.wh(a,b),function(c){return!!c})},Lbb=function(a,b,c){function d(R){var Y=R.hovercardButton;
if(!Y)return null;Y=Y.subscribeButtonRenderer;if(!Y)return null;var P=f(Y.unsubscribedButtonText),pa=f(Y.subscribedButtonText);if(Y.subscribed){var ma=f(Y.subscriberCountWithUnsubscribeText);var Ja=f(Y.subscriberCountText)}else ma=f(Y.subscriberCountText),Ja=f(Y.subscriberCountWithSubscribeText);var Na=null;if(R.signinEndpoint){Na=a4(R,"signinEndpoint","webNavigationEndpointData","url");if(!Na){var cb,Va;Na=null==(Va=g.L(null==(cb=Y.signInEndpoint)?void 0:cb.commandMetadata,g.V2))?void 0:Va.url}if(!Na)return null}return P&&
(pa||Na)?{subscribed:Y.subscribed,subscribeText:P,subscribeCount:ma,unsubscribeText:pa,unsubscribeCount:Ja,enabled:Y.enabled,signinUrl:Na,classic:R.useClassicSubscribeButton}:null}
function e(R){if(R){var Y=[],P=R.videoId;P&&Y.push("v="+P);(P=R.playlistId)&&Y.push("list="+P);(R=R.startTimeSeconds)&&Y.push("t="+R);return"/watch?"+Y.join("&")}}
function f(R){if(!R)return null;var Y=R.simpleText;return Y?Y:R.runs?g.wh(R.runs,function(P){return P.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,w=null,x=null,z=!1,B=null,E=null,G=null,F=null,K=null,N=null;if("VIDEO"===h)g.L(l,g.lK)?m=g.L(l,g.lK).url:(N=g.L(l,g.kK),m=e(N)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.L(l,g.lK)?m=g.L(l,g.lK).url:(N=g.L(l,g.kK),m=e(N)),n=!1,q=a,w=f(b.playlistLength);else if("CHANNEL"===
h){if(z=a4(l,"browseEndpoint","browseId"))x=z,m="/channel/"+x;n=!1;q="new";(z=!!b.isSubscribe)?B=d(b):E=f(b.subscribersText)}else"WEBSITE"===h?((G=a4(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(F=f(b.productPrice)),b.additionalFeesText&&(K=f(b.additionalFeesText)),(n=a4(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=a4(b,"title","accessibility","accessibilityData","label");var V=b.endpoint?b.endpoint.clickTrackingParams:null,
ba="";if(b.metadata){var U=f(b.metadata);U&&(ba=U)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ba,callToAction:f(b.callToAction),xS:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,dC:p,playlistLength:w,channelId:x,subscribeButton:B,subscribersText:E,isSubscribe:z,xt:m||null,z3:n,sessionData:V?{itct:V}:null,x8:q,CA:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:h4(b.impressionUrls||[],g4),n3:h4(b.hovercardShowUrls||[],g4),clickUrls:h4(l.loggingUrls||[],g4),visualElement:g.FC(b.trackingParams),productPrice:F,additionalFeesText:K,watchEndpoint:N||null}},Mbb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:h4(a.impressionUrls||[],g4),elements:h4(a.elements||[],function(d,e){return Lbb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.FC(a.trackingParams));return c},Nbb=function(a){g.fS.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.J=[];this.Y=!0;this.I=0;a=a.T();this.V=g.iI(a)||"profilepage"===a.Fa;this.ea=a.experiments.kb("web_rounded_thumbnails");this.events=new g.cG(this);g.D(this,this.events);this.events.S(this.player,g.cC("creatorendscreen"),this.onCueRangeEnter);this.events.S(this.player,g.dC("creatorendscreen"),this.onCueRangeExit);this.events.S(this.player,"resize",this.Eb);this.events.S(window,"focus",this.i7);this.load();var b=g.Le("STYLE");(g.Ae("HEAD")[0]||
document.body).appendChild(b);g.ab(this,function(){g.Ve(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Obb=function(a){return a.player.getVideoData().D?"current":a.V?"new":"current"},i4=function(a){return"creator-endscreen-editor"===a.player.T().playerStyle},Pbb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=Mbb(f,Obb(a))));j4(a,f)},
urlParams:{v:c},withCredentials:!0};a.V&&(c.urlParams.ptype="embedded");var d=b.Bw;d&&(c.postParams={ad_tracking:d});if(b=g.hCa(b))if(b=g.Od(b),b=g.Kd(b))a.B=g.Lw(b,c)},j4=function(a,b,c){c=void 0===c?!0:c;
a.player.Df("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.t(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&Qbb(a);c=[];d=new g.aC(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.T().u||(a.u=new g.T({G:"div",N:"ytp-ce-shadow"}),g.aR(a.player,a.u.element,4),a.C=new g.DO(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Rbb(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.aR(a.player,f.element,4);var h=new g.aC(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Sbb(a,f,e)}else g.GB(new g.Ix("buildEndscreenElement null",
e))}a.player.Ae(c);a.Eb()}},Qbb=function(a){var b=g.IC(),c=g.JC();
c&&b&&a.endscreen.visualElement&&g.qw(g.OM)(void 0,c,b,a.endscreen.visualElement)},Rbb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={G:"div",Ia:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.CA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-covering-image",X:k4(b)},{G:"div",N:"ytp-ce-covering-shadow-top"},{G:"a",N:"ytp-ce-covering-overlay",X:{href:l4(a,b.xt),tabindex:"-1"},W:[{G:"div",Ia:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.Lo(b.title||"")},qa:b.title},{G:"div",N:b.dC?"ytp-ce-live-video-duration":"ytp-ce-video-duration",qa:b.videoDuration||
void 0}]}]};c=new g.T(a);break;case "PLAYLIST":a={G:"div",Ia:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.CA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-covering-image",X:k4(b)},{G:"div",N:"ytp-ce-covering-shadow-top"},{G:"a",N:"ytp-ce-covering-overlay",X:{href:l4(a,b.xt),tabindex:"-1"},W:[{G:"div",Ia:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.Lo(b.title||"")},qa:b.title},{G:"div",N:"ytp-ce-playlist-count",W:[{G:"div",N:"ytp-ce-playlist-icon"},
{G:"div",N:"ytp-ce-playlist-count-text",qa:b.playlistLength||void 0}]}]}]};c=new g.T(a);break;case "CHANNEL":c={G:"div",Ia:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.CA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-expanding-overlay",W:[{G:"div",N:"ytp-ce-expanding-overlay-hider"},{G:"div",N:"ytp-ce-expanding-overlay-background"},{G:"div",N:"ytp-ce-expanding-overlay-content",W:[{G:"div",
N:"ytp-ce-expanding-overlay-body",W:[{G:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{G:"a",Ia:["ytp-ce-channel-title","ytp-ce-link"],X:{href:l4(a,b.xt),target:"_blank",tabindex:"-1",dir:g.Lo(b.title||"")},qa:b.title},b.subscribeButton?{G:"div",N:"ytp-ce-subscribe-container",W:[{G:"div",N:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{G:"div",N:"ytp-ce-channel-subscribers-text",qa:b.subscribersText}:"",b.metadata?{G:"div",Ia:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
qa:b.metadata}:""]}]}]}]},{G:"div",N:"ytp-ce-expanding-image",X:k4(b)}]};c=new g.T(c);var d=g.Be(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.vo(d,"ytp-ce-subscribe-button");if(a.player.T().u){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.gT(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={G:"div",Ia:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.CA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-expanding-overlay",W:[{G:"div",N:"ytp-ce-expanding-overlay-hider"},{G:"div",N:"ytp-ce-expanding-overlay-background"},{G:"div",N:"ytp-ce-expanding-overlay-content",W:[{G:"div",N:"ytp-ce-expanding-overlay-body",
W:[{G:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{G:"div",N:"ytp-ce-website-title",X:{dir:g.Lo(b.title||"")},qa:b.title},{G:"div",N:"ytp-ce-website-metadata",qa:b.metadata},{G:"a",Ia:["ytp-ce-website-goto","ytp-ce-link"],X:{href:l4(a,b.xt),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{G:"div",N:"ytp-ce-expanding-image",X:k4(b)},{G:"div",N:"ytp-ce-expanding-icon",X:Tbb(b.iconUrl)}]};c=new g.T(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",N:"ytp-ce-merchandise-price-container",
W:[{G:"div",N:"ytp-ce-merchandise-price",qa:b.productPrice}]},b.additionalFeesText&&c.W.push({G:"div",N:"ytp-ce-merchandise-additional-fees",qa:b.additionalFeesText})),a={G:"div",Ia:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.CA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-expanding-overlay",W:[{G:"div",N:"ytp-ce-expanding-overlay-hider"},{G:"div",N:"ytp-ce-expanding-overlay-background"},{G:"div",N:"ytp-ce-expanding-overlay-content",
W:[{G:"div",N:"ytp-ce-expanding-overlay-body",W:[{G:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{G:"div",N:"ytp-ce-merchandise-title",X:{dir:g.Lo(b.title||"")},qa:b.title},c,{G:"div",N:"ytp-ce-merchandise-metadata",qa:b.metadata},{G:"a",Ia:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:l4(a,b.xt),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{G:"div",N:"ytp-ce-expanding-image",X:k4(b)},{G:"div",N:"ytp-ce-merchandise-invideo-cta-container",W:[{G:"div",N:"ytp-ce-merchandise-invideo-cta",
qa:b.callToAction||void 0}]}]},c=new g.T(a)}b.isPlaceholder&&g.vo(c.element,"ytp-ce-placeholder");return c},k4=function(a){if(a.xS)var b=a.xS.thumbnails;
return Tbb(b?b[b.length-1].url:null)},Tbb=function(a){return a?{style:"background-image: url("+a+")"}:{}},Sbb=function(a,b,c){function d(m){m&&(b.Pa("blur",function(){"none"!=m.style.display&&a.Y&&m.focus()}),b.S(m,"focus",f),b.S(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.vo(b.element,"ytp-ce-force-expand"),m4(a,c.id,!0)):(g.xo(b.element,"ytp-ce-force-expand"),g.xo(b.element,"ytp-ce-element-hover"),m4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Pa("mouseenter",function(){Ubb(a,b,c)});
b.Pa("mouseleave",function(){Vbb(a,b,c)});
a.player.T().u||b.Pa("click",function(){g.vo(b.element,"ytp-ce-element-hover")});
b.Pa("click",function(m){Wbb(a,c,m)});
b.Pa("keypress",function(m){Wbb(a,c,m)});
b.Pa("focus",function(){Ubb(a,b,c)});
b.Pa("blur",function(){Vbb(a,b,c)});
b.Pa("touchstart",function(){Ubb(a,b,c)});
var l=g.Fe("ytp-ce-expanding-overlay-hider",b.element);l&&b.S(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.xo(b.element,"ytp-ce-element-hover");g.xo(b.element,"ytp-ce-force-expand")});
b.Pa("keydown",function(m){a.Y=9===m.keyCode&&!m.shiftKey});
d(g.Fe("ytp-sb-subscribe",b.element));d(g.Fe("ytp-sb-unsubscribe",b.element));b.Pa("focus",f);b.Pa("blur",h)},Wbb=function(a,b,c){if(b.xt&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.uo(d,"ytp-ce-element");){g.uo(d,"subscribe-label")&&Xbb(a,b);
if(g.uo(d,"ytp-ce-channel-subscribe"))return;d=g.We(d)}if(!d||g.uo(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Vbb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.x8)Xbb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Od(l4(a,b.xt)),g.CL(g.Kd(c),void 0,b.sessionData);else{var e=g.AI(a.player.T())||a.player.getVideoData().D,f=function(){var h=l4(a,b.xt),l=b.sessionData,m=b.watchEndpoint,n=g.xw(h);e&&n&&(n.v||n.list)?a.player.Dn(n.v,
l,n.list,!1,void 0,m||void 0):g.AL(h,l)};
Xbb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},l4=function(a,b){a=a.player.T();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.JI(a)+b}else return"";return b},Ubb=function(a,b,c){g.uo(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.vo(b.element,"ytp-ce-element-hover"):a.player.T().u?(new g.no(function(){g.vo(b.element,"ytp-ce-element-hover")},200)).start():g.vo(b.element,"ytp-ce-element-hover"),n4(a,c.n3),m4(a,c.id,!0))},Vbb=function(a,b,c){g.xo(b.element,"ytp-ce-element-hover");
g.xo(b.element,"ytp-ce-force-expand");m4(a,c.id,!1)},m4=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.t(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.zo(a.j[e].element,"ytp-ce-element-shadow-show",c)},n4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||i4(a))c&&c();else{b=Ybb(a,b);var e=0,f=!1,h=new g.no(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.zz(b[a],d)}},Xbb=function(a,b,c){n4(a,b.clickUrls,c);
(a=g.JC())&&b.z3&&g.VM(a,b.visualElement)},Ybb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Zbb(b[d],c));return a},Zbb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},$bb=function(a){return"string"===typeof a?a:""},o4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},acb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},p4=function(a){return a.value?a.value:null},q4=function(a){if(!a)return null;
var b=g.Od($bb(a.value));b=g.Kd(b);if(!b)return null;var c=o4(a.target,bcb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new acb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},ccb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},fcb=function(a){if(!a)return null;
var b=o4(a.type,dcb),c=o4(a.trigger,ecb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=q4(a?a:null);return b?new ccb(b,c,a):null},gcb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},hcb=function(a,b){return g.jb(a.action,b)},icb=function(a,b){this.context=a;
this.j=b},jcb=function(a){return a.customMessage?r4("div","iv-card-message",a.customMessage):""},s4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",N:"iv-card-image",X:{style:a},W:c}},kcb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.t(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(r4("li","",c.value));return{G:"ul",N:"iv-card-meta-info",W:b}},r4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Lo(c);return{G:a,X:b,qa:c}},lcb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.LA&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.LA+");");c.dir=g.Lo(a.customMessage);var d=[{G:"span",qa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",N:"iv-card-link-icon"}));return{G:"div",Ia:b,X:c,W:d}},t4=function(a,b,c,d){if(d){b=g.t(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.Oi.click,5)}},mcb=function(a,b){this.merchant=a;
this.price=b},ncb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},ocb=function(a,b){return b?b:ncb(a)?"current":"new"},u4=function(a,b){g.C.call(this);
var c=this;this.element=a;this.context=b;this.tb=!1;this.Xa=new Map;this.eb=new Map;this.context.F.addEventListener(g.cC("annotations_module"),function(d){(d=c.Xa.get(d))&&d.apply(c)});
this.context.F.addEventListener(g.dC("annotations_module"),function(d){(d=c.eb.get(d))&&d.apply(c)})},v4=function(a,b,c,d,e,f,h){a.context.j.Pa(b,"click",function(l){a.wI(c,d,e,f||[],h||0,l)});
a.context.j.Pa(b,"touchstart",function(){a.tb=!1});
a.context.j.Pa(b,"touchmove",function(){a.tb=!0})},pcb=function(a){var b;
return(null==(b=g.L(a,g.lK))?0:b.url)?g.L(a,g.lK).url:(a=g.L(a,g.kK))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},w4=function(a,b,c){return{VT:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
rX:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
GH:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},qcb=function(a,b,c){u4.call(this,b,c);
var d=this;this.F=a;this.eventId=null;this.Ra=this.ac=this.B=this.isInitialized=!1;this.ya=null;this.cards=[];this.zb=this.V=this.Ma=this.D=this.Sa=this.j=null;this.ea=[];this.oa=this.J=this.Rf=this.Ja=null;this.I=0;this.Fa=new g.no(function(){},c.Z.ah?4E3:3E3);
g.D(this,this.Fa);this.jb=new g.no(function(){});
g.D(this,this.jb);this.Aa=new icb(c,function(e,f,h,l,m,n){v4(d,e,f,h,l,m,n)});
this.Y=new g.T({G:"div",N:"iv-drawer",X:{id:"iv-drawer"},W:[{G:"div",N:"iv-drawer-header",X:{"aria-role":"heading"},W:[{G:"span",N:"iv-drawer-header-text"},{G:"button",Ia:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",N:"iv-drawer-content"}]});g.D(this,this.Y);this.C=this.Y.element;this.ib=new g.DO(this.Y,330);g.D(this,this.ib);this.Rb=g.Fe("iv-drawer-header-text",this.C);this.u=g.Fe("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.ac&&x4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.ac=d.B)&&y4(d)});
this.F.addEventListener("videodatachange",this.us.bind(this))},rcb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){x4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){y4(a)});
var c=b.headerText;g.Ye(a.Rb,c);a.V&&a.V.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ja=g.FC(b.trackingParams);a.J=g.FC(b.closeTrackingParams);a.Rf=g.FC(b.iconTrackingParams)},scb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I,d=a.F.T().experiments.kb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.kC(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,Oi:{},ao:null,Tk:e.trackingParams?g.FC(e.trackingParams):null,Rf:f&&f.trackingParams?g.FC(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
LA:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};z4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.kC(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:A4(a,c,b,f),sponsored:!1,Oi:w4(f,e,f.command),ao:f.trackingParams?g.FC(f.trackingParams):null,Tk:e.trackingParams?g.FC(e.trackingParams):null,Rf:l&&l.trackingParams?g.FC(l.trackingParams):null,imageUrl:B4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.kC(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,LA:null,title:f.title?g.kC(f.title):"",customMessage:f.callToAction?g.kC(f.callToAction):"",url:g.L(f.command,g.lK).url?q4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.L(f.command,g.lK).url}):null,onClickCommand:null};z4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.kC(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:A4(a,c,b,e),sponsored:!1,Oi:w4(e,f,e.endpoint),ao:e.trackingParams?g.FC(e.trackingParams):null,Tk:f.trackingParams?g.FC(f.trackingParams):null,Rf:l&&l.trackingParams?g.FC(l.trackingParams):null,channelId:g.L(e.endpoint,C4).browseId,customMessage:e.customText?g.kC(e.customText):null,kW:B4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.kC(e.channelName):"",metaInfo:[e.subscriberCountText?g.kC(e.subscriberCountText):""],url:q4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.L(e.endpoint,C4).canonicalBaseUrl?g.L(e.endpoint,C4).canonicalBaseUrl:"/channel/"+g.L(e.endpoint,C4).browseId}),onClickCommand:null};z4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.kC(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:A4(a,c,b,e),sponsored:!1,Oi:w4(e,f,e.action),ao:e.trackingParams?g.FC(e.trackingParams):null,Tk:f.trackingParams?g.FC(f.trackingParams):null,Rf:l&&l.trackingParams?g.FC(l.trackingParams):null,GD:B4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.kC(e.customMessage):null,playlistVideoCount:g.kC(e.playlistVideoCount),title:e.playlistTitle?g.kC(e.playlistTitle):"",metaInfo:[e.channelName?g.kC(e.channelName):
"",e.videoCountText?g.kC(e.videoCountText):""],url:q4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:pcb(e.action)}),onClickCommand:null};z4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.kC(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:A4(a,c,b,e),sponsored:!1,Oi:w4(e,f,e.action),ao:e.trackingParams?g.FC(e.trackingParams):null,Tk:f.trackingParams?g.FC(f.trackingParams):null,Rf:l&&l.trackingParams?g.FC(l.trackingParams):null,GD:B4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.kC(e.lengthString):null,customMessage:e.customMessage?g.kC(e.customMessage):null,title:e.videoTitle?g.kC(e.videoTitle):"",metaInfo:[e.channelName?g.kC(e.channelName):
"",e.viewCountText?g.kC(e.viewCountText):""],isLiveNow:!!e.badge,url:q4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:pcb(e.action)}),onClickCommand:null};z4(a,b)}}}}}a.I++},B4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},A4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},ucb=function(a,b){if(b=tcb(a,b))b===a.j&&(a.j=null),a.F.removeCueRange(b.Zf.id),g.Ve(b.bK),g.rb(a.cards,b),a.EE(),D4(a)},x4=function(a,b,c){if(!a.B){a.ib.show();
a.Sa=new g.no(function(){g.vo(a.context.F.getRootNode(),g.DW.IV_DRAWER_OPEN)},0);
a.Sa.start();a.ya=g.Qz(a.u,"mousewheel",function(h){a.Fa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.JC();d&&a.Ja&&a.J&&g.TM(d,[a.Ja,a.J]);b={TRIGGER_TYPE:b};for(var e=g.t(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.FU||(f.FU=!0,vcb(a.context.logger,f.Zf.Oi.VT,b)),d&&g.TM(d,[f.Zf.ao]);$3(a.F);c&&(a.D=new g.no(function(){a.Ma=a.V;a.zb.focus()},330),a.D.start())}},y4=function(a){a.B&&(a.ib.hide(),g.Rz(a.ya),a.ya=null,g.xo(a.context.F.getRootNode(),g.DW.IV_DRAWER_OPEN),a.B=!1,$3(a.F),a.D&&a.D.stop(),a.D=new g.no(function(){a.Ma&&(a.Ma.focus(),a.Ma=null)},330),a.D.start())},xcb=
function(a){g.wo(a.wb(),[g.DW.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.aR(a.F,a.C,5);wcb(a);a.V=g.Fe("ytp-cards-button",a.F.getRootNode());a.zb=g.Fe("iv-drawer-close-button",a.C);a.isInitialized=!0},wcb=function(a){var b=g.Fe("iv-drawer-close-button",a.C);
a.context.j.Pa(b,"click",a.z1,a);a.context.j.Pa(a.u,"touchend",function(){a.Fa.start()});
a.context.j.Pa(a.u,"scroll",a.O1,a);a.context.u.subscribe("onHideControls",function(){a.Ra=!0});
a.context.u.subscribe("onShowControls",function(){a.Ra=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ra=g.uo(a.F.getRootNode(),"ytp-autohide")});
a.ea.push(g.jA("iv-button-shown",a.L3,a));a.ea.push(g.jA("iv-button-hidden",a.K3,a));a.ea.push(g.jA("iv-teaser-shown",a.cZ,a));a.ea.push(g.jA("iv-teaser-hidden",a.M3,a));a.ea.push(g.jA("iv-teaser-clicked",a.bZ,a))},ycb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.L(b.onClickCommand,g.q9a))?void 0:c.targetId)?(a.oa=b,!0):!1},zcb=function(a,b){a.oa=b;
var c=a.F.getVideoData();if(!c)return!1;c=a.F.K("embeds_web_enable_video_data_refactoring_offline_and_progress_bar")?g.EJ(c):c.multiMarkersPlayerBarRenderer;if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.L(h[0],g.WNa))?void 0:d.timeRangeStartMillis)||0,a.oa=null,!0}return!1},
z4=function(a,b){if(!ycb(a,b)||zcb(a,b)){var c=Acb(a,b);
if(c){var d={Zf:b,bK:c.element,FU:!1};if(!b.onClickCommand){a.isInitialized||xcb(a);ucb(a,b.id);var e=Bcb(a,d);g.zb(a.cards,e,0,d);c.Da(a.u,e);a.EE()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,D4(a),Ccb(a,d),x4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.F.getCurrentTime(),5E3>c&&c>b.startMs&&Dcb(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){Dcb(a,d)}),D4(a))}}},Acb=function(a,b){switch(b.type){case "simple":var c=a.Aa;
var d=b.displayDomain?{G:"div",N:"iv-card-image-text",qa:b.displayDomain}:void 0;var e=lcb(b);d={G:"div",Ia:["iv-card"],W:[{G:"a",N:"iv-click-target",X:{href:b.url?p4(b.url)||"":""},W:[s4(b.imageUrl,d),{G:"div",N:"iv-card-content",W:[r4("h2",void 0,b.title),e]}]}]};d=new g.T(d);t4(c,g.Ce("iv-click-target",d.element),b,b.url);b=d;break;case "collaborator":c=a.Aa;d={G:"div",Ia:["iv-card","iv-card-channel"],W:[{G:"a",Ia:["iv-click-target"],X:{href:p4(b.url)||"","data-ytid":b.channelId},W:[s4(b.kW),{G:"div",
N:"iv-card-content",W:[jcb(b),{G:"h2",N:"iv-card-primary-link",qa:b.title},kcb(b)]}]}]};d=new g.T(d);t4(c,g.Ce("iv-click-target",d.element),b,b.url);b=d;break;case "playlist":c=a.Aa;d={G:"div",Ia:["iv-card","iv-card-playlist"],W:[{G:"a",N:"iv-click-target",X:{href:p4(b.url)||""},W:[s4(b.GD,{G:"div",N:"iv-card-image-overlay",W:[{G:"span",N:"iv-card-playlist-video-count",qa:b.playlistVideoCount}]}),{G:"div",N:"iv-card-content",W:[jcb(b),r4("h2","iv-card-primary-link",b.title),kcb(b)]}]}]};d=new g.T(d);
t4(c,g.Ce("iv-click-target",d.element),b,b.url);b=d;break;case "productListing":c=a.Aa;var f=!g.pb(b.offers);d=["iv-card"];e="";var h=lcb(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({G:"div",N:"iv-card-offer-price",qa:h.price}),h.merchant&&f.push({G:"div",N:"iv-card-offer-merchant",qa:h.merchant}),h={G:"div",W:f});f=b.url?p4(b.url)||"":"";d={G:"div",Ia:d,X:{tabindex:"0"},W:[{G:"a",Ia:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{G:"div",N:"iv-card-content",W:[b.sponsored?{G:"div",N:"iv-card-sponsored",W:["Sponsored",{G:"div",N:"iv-ad-info-container",W:[{G:"div",N:"iv-ad-info",qa:"{{adInfo}}"},{G:"div",N:"iv-ad-info-icon-container",W:[{G:"div",N:"iv-ad-info-icon"},{G:"div",N:"iv-ad-info-callout"}]}]}]}:"",{G:"a",N:"iv-click-target",X:{href:f},W:[r4("h2",e,b.title),h]}]}]};d=new g.T(d);e=g.Le("span");g.Ye(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
d.ke(e,"adInfo");t4(c,g.Ce("iv-click-target",d.element),b,b.url);b=d;break;case "video":c=a.Aa;d=b.videoDuration?{G:"span",N:"iv-card-video-duration",qa:b.videoDuration}:void 0;e=b.isLiveNow?{G:"span",Ia:["yt-badge","yt-badge-live"],qa:"LIVE NOW"}:null;f={G:"div",Ia:["iv-card","iv-card-video"],W:[{G:"a",N:"iv-click-target",X:{href:(null==(h=b.url)?void 0:p4(h))||""},W:[s4(b.GD,d),{G:"div",N:"iv-card-content",W:[jcb(b),r4("h2","iv-card-primary-link",b.title),kcb(b),e]}]}]};d=new g.T(f);t4(c,g.Ce("iv-click-target",
d.element),b,b.url);b=d;break;default:return null}a.F.T().experiments.kb("web_rounded_containers")&&g.vo(b.element,"ytp-rounded-info");return b},Bcb=function(a,b){if(0===a.cards.length)return 0;
a=g.lb(a.cards,function(c){return b.Zf.startMs>c.Zf.startMs||b.Zf.startMs===c.Zf.startMs&&b.Zf.timestamp>=c.Zf.timestamp?!0:!1});
return-1===a?0:a+1},Ecb=function(a){return a.j?"productListing"===a.j.Zf.type:g.Xk(a.cards,function(b){return"productListing"===b.Zf.type})},D4=function(a){g.zo(a.F.getRootNode(),"ytp-cards-shopping-active",Ecb(a))},Dcb=function(a,b){if(!g.uo(a.F.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.JC(),d=a.j?a.j.Zf.Rf:a.Rf;
c&&d&&g.UM(c,[d]);a.j=b;D4(a)}(c=a.isInitialized&&"none"==a.wb().style.display)||(c=a.context.F.getPlayerState(),d=0===c&&0===a.context.F.getCurrentTime(),c=!(1===c||3===c||d));c||b.Zf.teaserDurationMs&&a.F.rz(!0,{teaserText:b.Zf.teaserText,durationMs:b.Zf.teaserDurationMs,onClickCommand:b.Zf.onClickCommand});a.jb.isActive()||((!a.B||!a.Fa.isActive()&&a.Ra)&&Ccb(a,b),a.jb.start(910+b.Zf.teaserDurationMs))}},Ccb=function(a,b){a.Y.vb?(b=new e4([0,
a.u.scrollTop],[0,b.bK.offsetTop],600,Dbb),a.context.B.Pa(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Pa(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.PN(a.Y,!0),a.u.scrollTop=b.bK.offsetTop,g.PN(a.Y,!1))},E4=function(a){return a.j&&a.j.Zf?a.j.Zf:a.cards[0]&&a.cards[0].Zf?a.cards[0].Zf:null},tcb=function(a,b){return g.jb(a.cards,function(c){return c.Zf.id===b})},F4=function(a,b,c){u4.call(this,a,b);
this.annotation=c;this.isActive=!1},Fcb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},G4=function(a,b,c){F4.call(this,a,b,c);
this.u=null;this.J=!1;this.B=null;this.C=!1;this.j=this.I=this.D=null},Gcb=function(a,b){var c=void 0===c?0:c;
var d=Bbb(b).width;g.Ml(b,d);c=new Jbb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Cbb);g.D(a,c);a.context.B.Pa(c,"begin",function(){g.Yl(b,!0)});
c.play()},Jcb=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ia:["iv-branding-context-name"],qa:b.channel_name}),d=a.createElement({G:"div",Ia:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.gT(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.F),a.j.Da(d));var f=a.createElement({G:"div",Ia:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Ia:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Yl(h,!1);a.context.Z.K("web_rounded_containers")&&g.vo(h,"ytp-rounded-branding-context");var l=a.createElement({G:"div",Ia:["branding-context-container-outer"]});l.appendChild(h);g.Gl(l,"right",b.image_width+"px");g.Se(a.wb(),l);a.B=new g.no(function(){Hcb(a,h,l)},500);
g.D(a,a.B);a.context.j.Pa(a.wb(),"mouseover",function(){Icb(a,h,l,f,b.image_height)});
a.context.j.Pa(a.wb(),"mouseout",function(){a.B.start()})}},Icb=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Xl(b);a.j||(b.style.width=g.Ll(f.width,!0),c.style.width=g.Ll(f.width,!0));g.Gl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Gl(d,"right","1px");a.C=!0;g.Yl(b,!0);a.D=new g.no(function(){g.vo(this.wb(),"iv-branding-active")},0,a);
a.D.start()}},Hcb=function(a,b,c){g.xo(a.wb(),"iv-branding-active");
a.I=new g.no(function(){g.Yl(b,!1);a.j||(c.style.width=g.Ll(0,!0))},250);
a.I.start();a.C=!1},Kcb=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.Z=c;this.videoData=d;this.logger=e;this.F=f;this.u=h},Lcb=function(a,b,c){F4.call(this,a,b,c);
var d=this;this.V=this.isCollapsed=this.Y=!1;this.I=5E3;this.u=this.B=this.j=this.C=null;this.J=this.createElement({G:"div",Ia:["iv-promo-contents"]});this.D=new g.no(function(){d.j.setAttribute("aria-hidden","true");g.Yl(d.B,!1);g.Yl(d.u,!0)},700,this);
g.D(this,this.D)},Ncb=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.wb().setAttribute("aria-hidden","true");a.wb().setAttribute("aria-label","Promotion");a.wb().tabIndex=0;var e=a.annotation.Ve(),f=b.image_url;if(f){var h=a.createElement({G:"div",Ia:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?
(f=a.createElement({G:"span",N:"iv-promo-video-duration",qa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",N:"iv-promo-playlist-length",qa:b.playlist_length.toString()}),h.appendChild(f));e&&v4(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",N:"iv-promo-txt"}),g.Zd(f,p4(e)),a.j=f):a.j=a.createElement({G:"div",N:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",W:[{G:"strong",qa:b.text_line_1}]});
var m=a.createElement({G:"p",W:[{G:"span",N:"iv-promo-link",qa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ia:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ia:["iv-button","iv-promo-button"],W:[{G:"span",N:"iv-button-content",qa:f}]});var p=a.createElement({G:"div",N:"iv-promo-button-container"});p.appendChild(f);e&&v4(a,a.wb(),e,a.annotation.id,b.session_data,void 0,c)}g.vo(a.j,"iv-click-target");
e&&v4(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",W:[{G:"span",qa:b.text_line_1}]}),m=a.createElement({G:"p",W:[{G:"strong",qa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ia:["yt-badge","iv-promo-badge-live"],qa:"LIVE NOW"})),g.vo(a.j,"iv-click-target"),e&&v4(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.J.appendChild(a.j);p&&a.J.appendChild(p);
c=a.createElement({G:"div",N:"iv-promo-actions"});a.u=a.createElement({G:"button",Ia:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.j.Pa(a.u,"click",function(q){Mcb(a,5E3,q)});
c.appendChild(a.u);g.Yl(a.u,!1);a.context.j.Pa(a.wb(),"mouseover",a.O2,a);a.context.j.Pa(a.wb(),"mouseout",a.N2,a);a.context.j.Pa(a.wb(),"touchend",function(q){Mcb(a,5E3,q)});
a.B=a.createElement({G:"button",Ia:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.j.Pa(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.J2:a.I2,a);c.appendChild(a.B);g.wo(a.wb(),d);h&&(g.Se(a.wb(),h),n&&h.appendChild(n));g.Se(a.wb(),a.J);g.Se(a.wb(),c)},Mcb=function(a,b,c){c.stopPropagation();
Ocb(a);Pcb(a,b);a.j.focus()},Qcb=function(a){a.isCollapsed||a.V||a.C||(g.vo(a.wb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},Ocb=function(a){a.D.stop();
a.isCollapsed&&(g.yo(a.wb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Yl(a.u,!1),g.Yl(a.B,!0))},Pcb=function(a,b){a.C||(a.C=g.yf(function(){Rcb(this);
Qcb(this)},b,a))},Rcb=function(a){a.C&&(g.Da.clearTimeout(a.C),a.C=null)},Scb=function(a){this.F=a},vcb=function(a,b,c){b&&(c?H4(a,b.map(function(d){return g.go(d,c)})):H4(a,b))},H4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.t(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.zz(m,f);d&&(e++,0!==d&&a.F.sendVideoStatsEngageEvent(d,f))},Tcb=function(a){g.fS.call(this,a);
var b=this;this.loadNumber=0;this.I={};this.logger=new Scb(this.player);this.D=new g.cG(this);this.C=this.mp=null;this.events=new g.cG(this);this.J=this.j=null;this.V=[];g.D(this,this.D);this.D.S(this.player,"onVideoAreaChange",function(){b.ma("onVideoAreaChange")});
this.D.S(this.player,"onHideControls",function(){b.ma("onHideControls")});
this.D.S(this.player,"onShowControls",function(){b.ma("onShowControls")});
this.D.S(this.player,"resize",function(d){b.ma("resize",d)});
this.D.S(this.player,"presentingplayerstatechange",function(d){b.ma("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.dZ,this);this.subscribe("resize",this.BG,this);this.player.T().Aa.subscribe("vast_info_card_add",this.SV,this);g.D(this,this.events);this.Y=this.createElement({G:"div",N:"video-custom-annotations"});this.u=new g.T({G:"div",Ia:["ytp-player-content","ytp-iv-player-content"]});g.D(this,this.u);g.aR(this.player,this.u.element,4);this.u.hide();this.B=new g.T({G:"div",Ia:["ytp-iv-video-content"]});g.D(this,this.B);a=this.createElement({G:"div",N:"video-annotations"});
a.appendChild(this.Y);this.B.element.appendChild(a);this.Uv()&&this.load();var c=this.createElement({G:"style"});(g.Ae("HEAD")[0]||document.body).appendChild(c);g.ab(this,function(){g.Ve(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Ucb=function(a){a=a.createElement({G:"div",
Ia:["annotation","annotation-type-custom"]});g.Yl(a,!1);return a},Vcb=function(a,b){b=!b.isCued()&&!g.S(b,1024);
g.PN(a.u,b);g.PN(a.B,b)},Wcb=function(a,b){for(var c={},d=g.t(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ia(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Wcb(a,e))}return c},$cb=function(a){var b=a.player.getVideoData();
if(b.Sa){var c=a.player.T().Aa.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Fw(h)&&h.responseXML?h.responseXML:null)&&Xcb(a,h)}};
g.Qx()&&(d.onFinish=Ycb(a,d.onFinish));d.postParams={ic_only:"1"};Zcb(d,c);g.Lw(b.Sa,d)}}},Zcb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.NA&&(a.postParams.ic_coll=b.NA);b.KE&&(a.postParams.ic_xml=b.KE);b.JD&&(a.postParams.ic_track=b.JD)},adb=function(a){var b=new g.T({G:"div"});
g.Yl(b.element,!1);var c=new qcb(a.player,b.element,I4(a));g.D(c,b);b.Da(a.u.element);c.vD();return c},I4=function(a){if(!a.J){var b=new Kbb(a);
g.D(a,b);var c=new g.Vj(a);g.D(a,c);a.J=new Kcb(b,c,a.player.T(),a.player.getVideoData(),a.logger,a.player,a.Lh)}return a.J},Xcb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.JC();if(e){var f=g.IC();f&&g.qw(g.ODa)(void 0,e,f,[g.FC(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Wcb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=o4(f.type,bdb),p=o4(f.style,cdb),q=$bb(f.data),r=0!==q.length?JSON.parse(q):{};var w=f.action;f=fcb;if(null==w)var x=null;else if(g.Ha(w)){l=[];for(var z=g.t(w),B=z.next();!B.done;B=z.next()){var E=f(B.value);
E&&l.push(E)}x=l}else{var G=f(w);x=G?[G]:[]}e=m&&n?new gcb(m,n,p,x,r):null}else e=null}catch(U){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var F=Ucb(f),K=null;switch(l.type){case "branding":if(f.player.T().Hd)break;f.u.element.appendChild(F);K=new G4(F,I4(f),l);break;case "promotion":g.aR(f.player,F,4),K=new Lcb(F,I4(f),l)}K&&K.vD();if(f=K)g.D(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=adb(a),g.D(a,a.j));if("card"===e.type){c=a.j;var N=e&&e.data&&e.data.card_type;
f=e.data;if(N)switch(l=f.tracking||{},l={VT:l.impression,click:l.click,close:l.close,rX:l.teaser_impression,GH:l.teaser_click},F=f.tracking_params||{},K=null,N){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Oi:l,ao:F.card?g.FC(F.card):null,Tk:F.teaser?g.FC(F.teaser):null,Rf:F.icon?g.FC(F.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,kW:f.image_url,title:f.title,metaInfo:f.meta_info,url:q4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};z4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Oi:l,ao:F.card?g.FC(F.card):null,Tk:F.teaser?
g.FC(F.teaser):null,Rf:F.icon?g.FC(F.icon):null,GD:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:q4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};z4(c,e);break;case "productListing":f.signin_url&&(K=q4({target:"current",value:f.signin_url}));N=[];for(var V=f.offers||[],ba=0;ba<V.length;ba++)N.push(new mcb(g.te(V[ba].merchant),g.te(V[ba].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Oi:l,ao:F.card?g.FC(F.card):null,Tk:F.teaser?g.FC(F.teaser):null,Rf:F.icon?g.FC(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,LA:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:q4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),H6a:K,G6a:f.signin_title?f.signin_title:void 0,F6a:f.signin_message?f.signin_message:void 0,offers:N,onClickCommand:null};z4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Oi:l,ao:F.card?g.FC(F.card):
null,Tk:F.teaser?g.FC(F.teaser):null,Rf:F.icon?g.FC(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,LA:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:q4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};z4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Oi:l,ao:F.card?g.FC(F.card):null,Tk:F.teaser?g.FC(F.teaser):null,Rf:F.icon?g.FC(F.icon):null,GD:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:q4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},z4(c,e)}}else rcb(a.j,e);c=!0}}c&&
($3(a.player),a.BG())},ddb=function(a,b){var c=!1;
a.j||(a.j=adb(a),g.D(a,a.j));for(var d=g.t(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(scb(a.j,e.cardRenderer),c=!0);c&&(c=a.j,d=b.headerText?g.kC(b.headerText):"",g.Ye(c.Rb,d),c.V&&c.V.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ja=b.trackingParams?g.FC(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.FC(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Rf=b.icon.infoCardIconRenderer.trackingParams?
g.FC(b.icon.infoCardIconRenderer.trackingParams):null,$3(a.player),a.BG())},edb=function(a,b,c,d,e){if(!a.player.T().Hd){var f=[];
b.navigationEndpoint&&g.L(b.navigationEndpoint,C4)&&g.L(b.navigationEndpoint,C4).browseId&&f.push(new ccb("openUrl","click",new acb("/channel/"+g.L(b.navigationEndpoint,C4).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.L(b.subscribeButton,
g.BK)){d.channel_id=g.L(b.subscribeButton,g.BK).channelId;var l;b=g.L(b.subscribeButton,g.BK);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.kC(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.kC(b.subscriberCountText))):(b.subscriberCountText&&(e=g.kC(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.kC(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.L(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.V2))?void 0:m.url)||"";l={subscribeText:g.kC(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.kC(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new gcb(c,"branding","branding",f,d);l=Ucb(a);a.u.element.appendChild(l);f=new G4(l,I4(a),f);f.vD();g.D(f,f);a.I[c]=f}},Ycb=function(a,b){return function(){var c=g.ya.apply(0,arguments);
a.isDisposed()||a.V.push(g.jo.Ai(function(){b.apply(null,g.u(c))}))}},fdb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.UQ.prototype.rz=g.ca(18,function(a,b){var c=g.xS(this.ub());c&&c.rz(a,b)});
var b4={},c4=null;g.Sa(e4,g.Ho);g.k=e4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.bd())return!1;d4(this);this.startTime=a=g.Ra();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.xG();this.zl("play");-1==this.j&&this.zl("resume");this.j=1;var b=g.Oa(this);b in b4||(b4[b]=this);Fbb();Gbb(this,a);return!0};
g.k.stop=function(a){d4(this);this.j=0;a&&(this.progress=1);Hbb(this,this.progress);this.zl("stop");this.xq()};
g.k.pause=function(){this.bd()&&(d4(this),this.j=-1,this.zl("pause"))};
g.k.ra=function(){0==this.j||this.stop(!1);this.zl("destroy");e4.Ef.ra.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.vI=function(){this.zl("animate")};
g.k.zl=function(a){this.dispatchEvent(new Ibb(a,this))};
g.Sa(Ibb,g.eb);g.Sa(f4,e4);f4.prototype.C=function(){};
f4.prototype.vI=function(){this.C();f4.Ef.vI.call(this)};
f4.prototype.xq=function(){this.C();f4.Ef.xq.call(this)};
f4.prototype.xG=function(){this.C();f4.Ef.xG.call(this)};
g.Sa(Jbb,f4);Jbb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var C4=new g.Zp("browseEndpoint");g.v(Kbb,g.C);g.k=Kbb.prototype;g.k.Pa=function(a,b,c,d){c=(0,g.Pa)(c,d||this.u);a=g.Qz(a,b,c);this.j.push(a);return a};
g.k.cG=function(a,b,c,d){c=(0,g.Pa)(c,d||this.u);a=g.Jqa(a,b,c);this.j.push(a);return a};
g.k.Gc=function(a){g.Rz(a);g.rb(this.j,a)};
g.k.Xf=function(){g.Rz(this.j);this.j.length=0};
g.k.ra=function(){this.Xf();g.C.prototype.ra.call(this)};g.v(Nbb,g.fS);g.k=Nbb.prototype;g.k.load=function(){g.fS.prototype.load.call(this);if(!i4(this)){var a=g.iCa(this.player.getVideoData());a?(a=Mbb(a,Obb(this)),j4(this,a,!1)):Pbb(this)}};
g.k.unload=function(){j4(this,null);this.B&&(this.B.abort(),this.B=null);g.fS.prototype.unload.call(this)};
g.k.qh=function(a,b){return i4(this)?"loadCustomEndscreenRenderer"===a?(a=Mbb(b,"new"),j4(this,a),!0):null:null};
g.k.getOptions=function(){return i4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Eb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<gdb.length;f++){var h=Math.abs(b.width-gdb[f]);if(-1===e||d>=h)e=f,d=h}d=hdb[e];this.u&&g.Gl(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Wl(e.element,m,f);g.Ml(e.element,n,p);this.ea&&(g.yo(e.element,idb),256<m||256<f?g.vo(e.element,"ytp-ce-large-round"):96<m||96<f?g.vo(e.element,"ytp-ce-medium-round"):g.vo(e.element,"ytp-ce-small-round"));g.yo(e.element,jdb);m=h.left+h.width/2;h=h.top+l/2;g.vo(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.yo(e.element,hdb);g.vo(e.element,d);(e=g.Be(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Gl(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())n4(this,this.endscreen.impressionUrls),(a=g.JC())&&this.endscreen.visualElement&&g.SM(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.vo(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.vo(b,"ytp-ce-shown");n4(this,c.impressionUrls);(b=g.JC())&&g.SM(b,c.visualElement);this.player.T().I&&this.player.Na("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.xo(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.xo(b,"ytp-ce-shown");this.player.T().I&&this.player.Na("endscreenelementhidden",a)}};
g.k.i7=function(a){var b=this;a.target===window&&(new g.no(function(){for(var c=g.t(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.yo(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var gdb=[346,426,470,506,570,640,853,1280,1920],hdb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),jdb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],idb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var bcb={Hla:"current",GIa:"new"};var dcb={CLOSE:"close",eMa:"openUrl",SUBSCRIBE:"subscribe"},ecb={mka:"click",CLOSE:"close",hva:"hidden",wQa:"rollOut",xQa:"rollOver",VRa:"shown"};gcb.prototype.Ve=function(){var a=hcb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var cdb={Yfa:"anchored",uY:"branding",CHANNEL:"channel",xla:"cta",kva:"highlightText",Vya:"label",PLAYLIST:"playlist",qOa:"popup",zUa:"speech",SUBSCRIBE:"subscribe",AXa:"title",VIDEO:"video",k2a:"website"},bdb={uY:"branding",ria:"card",Ina:"drawer",jva:"highlight",JEa:"marker",tPa:"promotion",TEXT:"text",K3a:"widget"};g.v(u4,g.C);g.k=u4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.aC(a,b,{id:c,namespace:"annotations_module"});d&&this.Xa.set(a,d);e&&this.eb.set(a,e);this.context.F.Ae([a])};
g.k.vD=function(){this.context.u.subscribe("resize",this.EE,this)};
g.k.wb=function(){return this.element};
g.k.wI=function(a,b,c,d,e,f){if(this.tb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Ve(this.wb())};
g.k.EE=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=p4(a);if(f){var h=ocb(f,a.target),l=function(){a.j&&e.context.F.pauseVideo();var m=e.context.videoData.D||!1,n=g.xw(f||"");m&&n&&(n.v||n.list)?e.context.F.Dn(n.v,b,n.list,!1):g.CL(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);H4(this.context.logger,c,l,d);ncb(f)||(c=g.JC(),d=b.itct,c&&d&&g.VM(c,g.FC(d)))}};
g.k.ra=function(){this.Xa.clear();this.eb.clear();g.C.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.T(a);g.D(this,a);return a.element};g.v(qcb,u4);g.k=qcb.prototype;g.k.us=function(){this.oa&&z4(this,this.oa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.F.getRootNode())?(a=g.Xl(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.EE=function(){var a=this.isAvailable();g.Yl(this.wb(),a);g.zo(this.context.F.getRootNode(),g.DW.IV_DRAWER_ENABLED,a);$3(this.F)};
g.k.destroy=function(){this.F.rz(!1);try{this.F.getRootNode().removeChild(this.C)}catch(a){}g.kA(this.ea);g.Rz(this.ya);this.Sa&&this.Sa.dispose();this.D&&this.D.dispose();u4.prototype.destroy.call(this)};
g.k.z1=function(){if(this.B){H4(this.context.logger,E4(this).Oi.close);var a=g.JC();a&&this.J&&g.VM(a,this.J);y4(this)}};
g.k.O1=function(){g.zo(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.L3=function(){var a=g.JC(),b=E4(this);b=b?b.Rf:this.Rf;a&&b&&g.TM(a,[b])};
g.k.K3=function(){var a=g.JC(),b=E4(this);b=b?b.Rf:this.Rf;a&&b&&g.UM(a,[b])};
g.k.cZ=function(){var a=E4(this);H4(this.context.logger,a.Oi.rX);var b=g.JC();b&&a&&g.TM(b,[a.Tk,a.Rf])};
g.k.M3=function(){var a=g.JC(),b=E4(this);a&&b&&g.UM(a,[b.Tk])};
g.k.bZ=function(a){var b=E4(this),c=g.JC();this.j?a?(a=this.context.logger,H4(a,b.Oi.GH),a.F.sendVideoStatsEngageEvent(4,void 0),c&&b.Tk&&g.VM(c,b.Tk)):(a=this.context.logger,H4(a,b.Oi.GH),a.F.sendVideoStatsEngageEvent(4,void 0),c&&b.Rf&&g.VM(c,b.Rf)):(a=this.context.logger,H4(a,b.Oi.GH),a.F.sendVideoStatsEngageEvent(4,void 0),c&&this.Rf&&g.VM(c,this.Rf))};g.v(F4,u4);F4.prototype.vD=function(){u4.prototype.vD.call(this);Fcb(this)};
F4.prototype.show=function(){u4.prototype.show.call(this);var a=g.JC(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.TM(a,[g.FC(b.itct)])};
F4.prototype.hide=function(){u4.prototype.hide.call(this);var a=g.JC(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.UM(a,[g.FC(b.itct)])};g.v(G4,F4);
G4.prototype.show=function(){if(!this.isActive){F4.prototype.show.call(this);if(!this.J){g.vo(this.wb(),"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ia:["branding-img","iv-click-target"],X:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Yl(this.u,!1);var b=this.createElement({G:"button",Ia:["branding-img-container","ytp-button"]});b.appendChild(this.u);this.wb().appendChild(b);var c=this.annotation.Ve();c&&v4(this,b,
c,this.annotation.id,a.session_data);Jcb(this,a);this.J=!0}g.Yl(this.wb(),!0);this.isActive=!0;this.u&&(Gcb(this,this.u),g.vo(this.context.F.getRootNode(),"ytp-branding-shown"))}};
G4.prototype.hide=function(){this.isActive&&(F4.prototype.hide.call(this),g.Yl(this.wb(),!1),this.isActive=!1,g.xo(this.context.F.getRootNode(),"ytp-branding-shown"))};
G4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);F4.prototype.destroy.call(this)};g.v(Lcb,F4);g.k=Lcb.prototype;g.k.show=function(){this.isActive||(F4.prototype.show.call(this),this.Y||(Ncb(this),this.Y=!0),g.Yl(this.wb(),!0),g.yf(function(){g.xo(this.wb(),"iv-promo-inactive")},100,this),this.wb().removeAttribute("aria-hidden"),this.isActive=!0,Rcb(this),Ocb(this),Pcb(this,this.I))};
g.k.hide=function(){this.isActive&&(g.vo(this.wb(),"iv-promo-inactive"),this.isActive=!1,this.wb().setAttribute("aria-hidden","true"))};
g.k.wI=function(a,b,c,d,e,f){return this.isCollapsed?!1:F4.prototype.wI.call(this,a,b,c,d,e,f)};
g.k.O2=function(a){this.V=!0;Mcb(this,500,a)};
g.k.N2=function(){this.V=!1;Qcb(this)};
g.k.I2=function(a){a.stopPropagation();this.hide()};
g.k.J2=function(a){a.stopPropagation();Rcb(this);this.isCollapsed=!0;g.vo(this.wb(),"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();F4.prototype.destroy.call(this)};g.v(Tcb,g.fS);g.k=Tcb.prototype;g.k.qh=function(a,b){if(!fdb(this.player.T().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.X6a(b))&&Xcb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(ucb(this.j,b),$3(this.player)),!0}return null};
g.k.getOptions=function(){return fdb(this.player.T().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Uv=function(){var a=this.player.T(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return b.D&&a.ea||a.K("embeds_enable_muted_autoplay")&&this.player.isMutedByMutedAutoplay()?!1:1===c&&!b.aR||a.Aa.get(b.videoId)||g.IK(b)||g.JK(b)?!0:!1};
g.k.BG=function(){if(this.B){var a=this.player.gb().getVideoContentRect(!0);g.Wl(this.B.element,a.width,a.height);g.Ml(this.B.element,a.left,a.top)}if(this.j){var b=this.player.vk();a=this.j;b=b.width;g.zo(a.C,"iv-drawer-small",426>=b);g.zo(a.C,"iv-drawer-big",1280<=b)}};
g.k.dZ=function(a){Vcb(this,a.state);g.S(a.state,2)&&(this.uj()&&this.Zn()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.rz(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.C=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Fw(h)&&h.responseXML?h.responseXML:null)&&(Xcb(b,h),g.vo(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.fS.prototype.load.call(this);Vcb(this,this.player.Fb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Qx()&&(a=Ycb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.C=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.T().Aa.get(d);f&&Zcb(e,f);f=f&&(f.KE||f.NA);if(!c.Zz||f)c.Sa?this.C=g.Lw(c.Sa,e):(this.mp=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.mp));
g.aR(this.player,this.B.element,4);this.BG();(f=g.IK(c))&&ddb(this,f);(f=g.JK(c))&&f.featuredChannel&&edb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Sa&&(this.mp&&(this.player.removeEventListener("videodatachange",this.mp),this.mp=null),this.C=g.Lw(b.Sa,a))};
g.k.unload=function(){this.player.Df("annotations_module");for(var a=g.t(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.J=null;this.j&&(this.j.destroy(),this.j=null,$3(this.player));this.C&&(this.C.abort(),this.C=null);this.I={};this.u.hide();g.fS.prototype.unload.call(this);this.B.detach();this.mp&&(this.player.removeEventListener("videodatachange",this.mp),this.mp=null)};
g.k.SV=function(a){a===this.player.getVideoData().videoId&&(this.loaded?$cb(this):this.load())};
g.k.uj=function(){return!!this.j&&this.j.isAvailable()};
g.k.Zn=function(){return!!this.j&&this.j.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.uj();this.j&&(a?c?x4(this.j,c,b):x4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):y4(this.j))};
g.k.rz=function(a,b){this.player.ma(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ra=function(){this.player.T().Aa.unsubscribe("vast_info_card_add",this.SV,this);g.xo(this.player.getRootNode(),g.DW.IV_DRAWER_OPEN);for(var a=this.V,b=g.jo,c=0,d=a.length;c<d;c++)b.tm(a[c]);this.V.length=0;g.fS.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.T(a);g.D(this,a);return a.element};g.eS("annotations_module",Tcb);g.eS("creatorendscreen",Nbb);})(_yt_player);
