(function(g){var window=this;'use strict';var tgb=function(a){g.T.call(this,{G:"div",N:"ytp-miniplayer-ui"});this.Sf=!1;this.player=a;this.S(a,"minimized",this.Wh);this.S(a,"onStateChange",this.KO)},ugb=function(a){g.fS.call(this,a);
this.u=new g.cG(this);this.j=new tgb(this.player);this.j.hide();g.aR(this.player,this.j.element,4);a.jg()&&(this.load(),g.zo(a.getRootNode(),"ytp-player-minimized",!0));this.player.K("web_rounded_containers")&&g.zo(a.getRootNode(),"ytp-rounded-miniplayer",!0)};
g.v(tgb,g.T);g.k=tgb.prototype;
g.k.KL=function(){this.tooltip=new g.KV(this.player,this);g.D(this,this.tooltip);g.aR(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Qc=new g.XS(this.player);g.D(this,this.Qc);this.lj=new g.T({G:"div",N:"ytp-miniplayer-scrim"});g.D(this,this.lj);this.lj.Da(this.element);this.S(this.lj.element,"click",this.CG);var a=new g.T({G:"button",Ia:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},W:[g.XN()]});g.D(this,a);a.Da(this.lj.element);this.S(a.element,"click",this.To);
a=new g.B2(this.player,this);g.D(this,a);a.Da(this.lj.element);this.wu=new g.T({G:"div",N:"ytp-miniplayer-controls"});g.D(this,this.wu);this.wu.Da(this.lj.element);this.S(this.wu.element,"click",this.CG);var b=new g.T({G:"div",N:"ytp-miniplayer-button-container"});g.D(this,b);b.Da(this.wu.element);a=new g.T({G:"div",N:"ytp-miniplayer-play-button-container"});g.D(this,a);a.Da(this.wu.element);var c=new g.T({G:"div",N:"ytp-miniplayer-button-container"});g.D(this,c);c.Da(this.wu.element);this.iW=new g.JU(this.player,
this,!1);g.D(this,this.iW);this.iW.Da(b.element);b=new g.HU(this.player,this);g.D(this,b);b.Da(a.element);this.nextButton=new g.JU(this.player,this,!0);g.D(this,this.nextButton);this.nextButton.Da(c.element);this.pj=new g.DV(this.player,this);g.D(this,this.pj);this.pj.Da(this.lj.element);this.Jc=new g.QU(this.player,this);g.D(this,this.Jc);g.aR(this.player,this.Jc.element,4);this.sG=new g.T({G:"div",N:"ytp-miniplayer-buttons"});g.D(this,this.sG);g.aR(this.player,this.sG.element,4);a=new g.T({G:"button",
Ia:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},W:[g.XN()]});g.D(this,a);a.Da(this.sG.element);this.S(a.element,"click",this.To);a=new g.T({G:"button",Ia:["ytp-miniplayer-replay-button","ytp-button"],X:{"aria-label":"Close"},W:[g.dO()]});g.D(this,a);a.Da(this.sG.element);this.S(a.element,"click",this.k6);this.S(this.player,"presentingplayerstatechange",this.td);this.S(this.player,"appresize",this.Eb);this.S(this.player,"fullscreentoggled",this.Eb);this.Eb()};
g.k.show=function(){this.kf=new g.lo(this.vv,null,this);this.kf.start();this.Sf||(this.KL(),this.Sf=!0);0!==this.player.getPlayerState()&&g.T.prototype.show.call(this);this.Jc.show();this.player.unloadModule("annotations_module")};
g.k.hide=function(){this.kf&&(this.kf.dispose(),this.kf=void 0);g.T.prototype.hide.call(this);this.player.jg()||(this.Sf&&this.Jc.hide(),this.player.loadModule("annotations_module"))};
g.k.ra=function(){this.kf&&(this.kf.dispose(),this.kf=void 0);g.T.prototype.ra.call(this)};
g.k.To=function(){this.player.stopVideo();this.player.Na("onCloseMiniplayer")};
g.k.k6=function(){this.player.playVideo()};
g.k.CG=function(a){if(a.target===this.lj.element||a.target===this.wu.element)g.EM(this.player.Fb())?this.player.pauseVideo():this.player.playVideo()};
g.k.Wh=function(){g.zo(this.player.getRootNode(),"ytp-player-minimized",this.player.jg())};
g.k.He=function(){this.Jc.xc();this.pj.xc()};
g.k.vv=function(){this.He();this.kf&&this.kf.start()};
g.k.td=function(a){g.S(a.state,32)&&this.tooltip.hide()};
g.k.Eb=function(){g.cV(this.Jc,0,this.player.gb().getPlayerSize().width,!1);g.RU(this.Jc)};
g.k.KO=function(a){this.player.jg()&&(0===a?this.hide():this.show())};
g.k.Cc=function(){return this.tooltip};
g.k.hg=function(){return!1};
g.k.ih=function(){return!1};
g.k.Qb=function(){return!1};
g.k.Gl=function(){return!1};
g.k.tD=function(){};
g.k.Jp=function(){};
g.k.Ox=function(){};
g.k.Dm=function(){return null};
g.k.pF=function(){return null};
g.k.sF=function(){return new g.je(0,0)};
g.k.FB=function(){return null};
g.k.vk=function(){return new g.Dl(0,0,0,0)};
g.k.handleGlobalKeyDown=function(){return!1};
g.k.handleGlobalKeyUp=function(){return!1};
g.k.Hv=function(a,b,c,d,e){var f=0,h=d=0,l=g.Xl(a);if(b){c=g.uo(b,"ytp-prev-button")||g.uo(b,"ytp-next-button");var m=g.uo(b,"ytp-play-button"),n=g.uo(b,"ytp-miniplayer-expand-watch-page-button");c?f=h=12:m?(b=g.Vl(b,this.element),h=b.x,f=b.y-12):n&&(h=g.uo(b,"ytp-miniplayer-button-top-left"),f=g.Vl(b,this.element),b=g.Xl(b),h?(h=8,f=f.y+40):(h=f.x-l.width+b.width,f=f.y-20))}else h=c-l.width/2,d=25+(e||0);b=this.player.gb().getPlayerSize().width;e=f+(e||0);l=g.be(h,0,b-l.width);e?(a.style.top=e+"px",
a.style.bottom=""):(a.style.top="",a.style.bottom=d+"px");a.style.left=l+"px"};
g.k.showControls=function(){};
g.k.hp=function(){};
g.k.Bl=function(){return!1};
g.k.uD=function(){};
g.k.vz=function(){};
g.k.Lq=function(){};
g.k.Kq=function(){};
g.k.yE=function(){};
g.k.Jr=function(){};g.v(ugb,g.fS);g.k=ugb.prototype;g.k.onVideoDataChange=function(){if(this.player.K("web_rounded_containers")&&this.player.getVideoData()){var a=this.player.getVideoAspectRatio(),b=16/9;a=a>b+.1||a<b-.1;g.zo(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",a)}};
g.k.create=function(){g.fS.prototype.create.call(this);this.u.S(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.k.Ok=function(){return!1};
g.k.load=function(){this.player.hideControls();this.j.show()};
g.k.unload=function(){this.player.showControls();this.j.hide()};g.eS("miniplayer",ugb);})(_yt_player);
